# Generated by Django 5.0.6 on 2024-08-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewdetails',
            options={'verbose_name_plural': '口コミ詳細'},
        ),
        migrations.AlterModelOptions(
            name='reviewitems',
            options={'verbose_name_plural': '口コミのレビュー項目'},
        ),
        migrations.AlterModelOptions(
            name='reviewrevisions',
            options={'verbose_name_plural': '口コミ修正履歴'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': '口コミ'},
        ),
    ]
