# Generated by Django 5.0.6 on 2024-08-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_product_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='is_active',
        ),
        migrations.AddField(
            model_name='reviews',
            name='status',
            field=models.IntegerField(choices=[(0, '未確認'), (1, '公開'), (2, '非公開')], default=0, verbose_name='公開ステータス'),
        ),
    ]
