# Generated by Django 5.0.6 on 2024-08-10 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_reviews_is_active_reviews_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewrevisions',
            options={'verbose_name_plural': '口コミ詳細の修正履歴'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-reviewed_at'], 'verbose_name_plural': '口コミ'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='レビュー回答日時'),
            preserve_default=False,
        ),
    ]
