# Generated by Django 5.0.6 on 2024-08-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_reviews_reviewed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='synergy',
            new_name='synergy_id',
        ),
    ]
