# Generated by Django 5.0.6 on 2024-08-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_rename_synergy_reviews_synergy_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviews',
            name='unique_review',
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('source', 'synergy_id'), name='unique_review'),
        ),
    ]
