# Generated by Django 5.0.6 on 2024-08-11 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_reviews_unique_review_reviews_unique_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdetails',
            old_name='review_text',
            new_name='_review_text',
        ),
        migrations.AlterField(
            model_name='reviewdetails',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_details', to='reviews.reviews'),
        ),
        migrations.AlterField(
            model_name='reviewrevisions',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_revisions', to='reviews.reviewdetails'),
        ),
    ]
