# Generated by Django 5.0.6 on 2024-08-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_rename_review_text_reviewdetails__review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdetails',
            name='_review_text',
            field=models.TextField(blank=True, null=True, verbose_name='レビュー本文'),
        ),
        migrations.AlterField(
            model_name='reviewitems',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviewitems',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewrevisions',
            name='review_text',
            field=models.TextField(blank=True, null=True, verbose_name='レビュー本文'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='synergy_id',
            field=models.CharField(max_length=100),
        ),
    ]
