# Generated by Django 5.0.6 on 2024-08-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_reviewdetails_reviews_rev_review__0c0df6_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='ReviewDetails',
            new_name='ReviewDetail',
        ),
        migrations.RenameModel(
            old_name='ReviewItems',
            new_name='ReviewItem',
        ),
        migrations.RenameModel(
            old_name='ReviewRevisions',
            new_name='ReviewRevision',
        ),
        migrations.AlterModelTableComment(
            name='review',
            table_comment='口コミの基本情報',
        ),
        migrations.AlterModelTableComment(
            name='reviewdetail',
            table_comment='各口コミの各項目に対する評価やコメントを管理',
        ),
        migrations.AlterModelTableComment(
            name='reviewrevision',
            table_comment='各口コミ詳細の修正履歴を管理',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_source__ef8cad_idx',
            old_name='reviews_rev_source__497c0c_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewdetail',
            new_name='reviews_rev_review__5021f7_idx',
            old_name='reviews_rev_review__0c0df6_idx',
        ),
    ]
