# Generated by Django 5.0.6 on 2024-08-11 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_rename_reviews_review_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='reviewdetail',
            table_comment='各口コミの各項目に対する評価やコメントを管理（更新不可）',
        ),
        migrations.RenameField(
            model_name='reviewdetail',
            old_name='_review_text',
            new_name='review_text',
        ),
        migrations.AlterField(
            model_name='reviewdetail',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_detail', to='reviews.review'),
        ),
    ]
