# Generated by Django 5.0.6 on 2024-08-11 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_rename_corporations_corporation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='mst_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.product', verbose_name='保険商品マスタ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.corporation', verbose_name='集計元'),
        ),
        migrations.AlterField(
            model_name='reviewrevision',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_revisions', to='reviews.reviewdetail', verbose_name='口コミ詳細'),
        ),
        migrations.AlterField(
            model_name='reviewrevision',
            name='revised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.staff', verbose_name='修正者'),
        ),
    ]
