# Generated by Django 5.0.6 on 2024-08-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_remove_review_product_review_mst_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公開日時'),
        ),
        migrations.AddField(
            model_name='review',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.staff', verbose_name='公開者'),
        ),
    ]
